// Generated from the official base/bridge Solana program IDL (tests/fixtures/bridge.idl.json).
// Regenerate if the vendored IDL changes; tests/unit/idl-parity.test.ts checks they stay in sync.
export const BRIDGE_PROGRAM_ERRORS: Record<number, readonly [name: string, message: string]> = {
  12000: ["BridgePaused", "Bridge is currently paused"],
  12001: ["IncorrectBridgeProgram", "Incorrect bridge program"],
  12002: ["IncorrectGasFeeReceiver", "Incorrect gas fee receiver"],
  12100: ["UnauthorizedInitialization", "Only the upgrade authority can initialize the bridge"],
  12101: ["UnauthorizedConfigUpdate", "Unauthorized to update configuration"],
  12200: ["BufferUnauthorizedClose", "Only the owner can close this buffer"],
  12201: ["BufferUnauthorizedAppend", "Only the owner can append to this buffer"],
  12202: ["BufferMaxSizeExceeded", "Call buffer size exceeds maximum allowed size"],
  12300: ["InvalidRecoveryId", "Invalid recovery ID"],
  12301: ["SignatureVerificationFailed", "Signature verification failed"],
  12302: ["InsufficientBaseSignatures", "Insufficient base oracle signatures to meet threshold"],
  12303: ["InsufficientPartnerSignatures", "Insufficient partner oracle signatures to meet threshold"],
  12400: ["InvalidProof", "Invalid proof"],
  12401: ["MmrShouldBeEmpty", "MMR should be empty"],
  12402: ["EmptyMmr", "MMR is empty"],
  12403: ["LeafMountainNotFound", "Leaf's mountain not found"],
  12404: ["InsufficientProofElementsForIntraMountainPath", "Insufficient proof elements for intra-mountain path"],
  12405: ["InsufficientProofElementsForOtherMountainPeaks", "Insufficient proof elements for other mountain peaks"],
  12406: ["UnusedProofElementsRemaining", "Unused proof elements remaining"],
  12407: ["NoPeaksFoundForNonEmptyMmr", "No peaks found for non-empty MMR"],
  12500: ["InvalidMessageHash", "Invalid message hash"],
  12501: ["AlreadyExecuted", "Message already executed"],
  12502: ["IncorrectBlockNumber", "Incorrect block number"],
  12600: ["MintDoesNotMatchLocalToken", "Mint does not match local token"],
  12601: ["TokenAccountDoesNotMatchTo", "Token account does not match to address"],
  12602: ["IncorrectTokenVault", "Incorrect token vault"],
  12603: ["MintIsWrappedToken", "Mint is a wrapped token"],
  12604: ["IncorrectTo", "Incorrect to"],
  12605: ["IncorrectSolVault", "Incorrect sol vault"],
  12700: ["RemoteTokenNotFound", "Remote token not found"],
  12701: ["ScalerExponentNotFound", "Scaler exponent not found"],
  12702: ["InvalidRemoteToken", "Invalid remote token"],
  12703: ["InvalidScalerExponent", "Invalid scaler exponent"],
  12704: ["MintIsNotFromToken2022", "Mint is not a token 2022 mint"],
  12705: ["MintIsNotWrappedTokenPda", "Mint is not a valid wrapped token PDA"],
  12800: ["InvalidThreshold", "Threshold must be <= number of signers"],
  12801: ["TooManySigners", "Too many signers (max 32)"],
  12802: ["DuplicateSigner", "Duplicate signer found"],
  12803: ["InvalidPartnerThreshold", "Invalid partner threshold"],
  12804: ["InvalidDenominator", "Invalid denominator"],
  12805: ["InvalidWindowDurationSeconds", "Invalid window duration seconds"],
  12806: ["InvalidGasCostScalerDp", "Invalid gas cost scaler dp"],
  12807: ["InvalidBlockIntervalRequirement", "Invalid block interval requirement"],
  12900: ["CreationWithNonZeroTarget", "Creation with non-zero target"],
  12901: ["ZeroAddress", "Zero address"],
};
